# fluent-bit-values.yaml
kind: DaemonSet

# Configure Fluent Bit inputs, filters, and outputs
config:
  inputs: |
    [INPUT]
        Name    systemd
        Tag     uio_logs_5000_systemd
        db      /var/lib/fluent-bit/storage/systemd.db
        db.Sync   Normal

        Mem_Buf_Limit 100MB
        storage.type filesystem
        storage.pause_on_chunks_overlimit on

        Read_From_Tail On
        Lowercase On
        Threaded true



  filters: |
    [FILTER]
        Name modify
        Match uio_logs_5000_systemd

        Add dataops.data_processor dataops-logs-systemd

        Add event.module systemd
        Add event.provider systemd
        Add event.dataset systemd.journald

        Add data_stream.namespace prod
        Add data_stream.dataset systemd.journald

        Add service.name linux-systemd

    [FILTER]
        Name nest
        Match *

        Operation nest
        Wildcard dataops.*
        Nest_under dataops
        Remove_prefix dataops.

    [FILTER]
        Name nest
        Match *

        Operation nest
        Wildcard event.*
        Nest_under event
        Remove_prefix event.

    [FILTER]
        Name nest
        Match *

        Operation nest
        Wildcard data_stream.*
        Nest_under data_stream
        Remove_prefix data_stream.

    [FILTER]
        Name nest
        Match *

        Operation nest
        Wildcard service.*
        Nest_under service
        Remove_prefix service.

  outputs: |
    [OUTPUT]
        Name stdout
        Match kube.*
