apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fluent-bit-cert
  namespace: logging
spec:
  secretName: fluent-bit-tls-secret # Generated automatically
  issuerRef:
    name: my-internal-ca-issuer
    kind: Issuer
  commonName: fluent-bit.logging.svc
  dnsNames:
  - fluent-bit.logging.svc.cluster.local
